In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.neighbors import LSHForest

In [3]:
>>> X_train = [[5, 5, 2], [21, 5, 5], [1, 1, 1], [8, 9, 1], [6, 10, 2]]
>>> X_test = [[9, 1, 6], [3, 1, 10], [7, 10, 3], [1,1,1]]
>>> lshf = LSHForest(random_state=42)
>>> lshf.fit(X_train)  
LSHForest(min_hash_match=4, n_candidates=50, n_estimators=10,
          n_neighbors=5, radius=1.0, radius_cutoff_ratio=0.9,
          random_state=42)
>>> distances, indices = lshf.kneighbors(X_test, n_neighbors=2)
print distances                                        
print indices


[[  6.93930993e-02   1.49609594e-01]
 [  2.29325364e-01   4.81000704e-01]
 [  4.89443707e-03   1.48191329e-02]
 [ -2.22044605e-16   5.71909584e-02]]
[[1 2]
 [2 0]
 [4 0]
 [2 0]]


In [4]:
import time
import numpy as np
from sklearn.datasets.samples_generator import make_blobs
from sklearn.neighbors import LSHForest
from sklearn.neighbors import NearestNeighbors

# Initialize size of the database, iterations and required neighbors.
n_samples = 10000
n_features = 100
n_iter = 30
n_neighbors = 100
rng = np.random.RandomState(42)

# Generate sample data
X, _ = make_blobs(n_samples=n_samples, n_features=n_features,
                  centers=10, cluster_std=5, random_state=0)

# Set `n_estimators` values
n_estimators_values = np.linspace(1, 30, 5).astype(np.int)
accuracies_trees = np.zeros(n_estimators_values.shape[0], dtype=float)

# Calculate average accuracy for each value of `n_estimators`
for i, n_estimators in enumerate(n_estimators_values):
    lshf = LSHForest(n_candidates=500, n_estimators=n_estimators,
                     n_neighbors=n_neighbors)
    nbrs = NearestNeighbors(n_neighbors=n_neighbors, algorithm='brute')

    lshf.fit(X)
    nbrs.fit(X)
    for j in range(n_iter):
        query = X[rng.randint(0, n_samples)]
        neighbors_approx = lshf.kneighbors(query, return_distance=False)
        neighbors_exact = nbrs.kneighbors(query, return_distance=False)

        intersection = np.intersect1d(neighbors_approx,
                                      neighbors_exact).shape[0]
        ratio = intersection/float(n_neighbors)
        accuracies_trees[i] += ratio

    accuracies_trees[i] = accuracies_trees[i]/float(n_iter)

/Users/ajay/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/ajay/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/ajay/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  

In [5]:
# Set `n_candidate` values
n_candidates_values = np.linspace(10, 500, 5).astype(np.int)
accuracies_c = np.zeros(n_candidates_values.shape[0], dtype=float)

# Calculate average accuracy for each value of `n_candidates`
for i, n_candidates in enumerate(n_candidates_values):
    lshf = LSHForest(n_candidates=n_candidates, n_neighbors=n_neighbors)
    nbrs = NearestNeighbors(n_neighbors=n_neighbors, algorithm='brute')
    # Fit the Nearest neighbor models
    lshf.fit(X)
    nbrs.fit(X)
    for j in range(n_iter):
        query = X[rng.randint(0, n_samples)]
        # Get neighbors
        neighbors_approx = lshf.kneighbors(query, return_distance=False)
        neighbors_exact = nbrs.kneighbors(query, return_distance=False)

        intersection = np.intersect1d(neighbors_approx,
                                      neighbors_exact).shape[0]
        ratio = intersection/float(n_neighbors)
        accuracies_c[i] += ratio

    accuracies_c[i] = accuracies_c[i]/float(n_iter)

/Users/ajay/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/ajay/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/ajay/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  

In [22]:
from annoy import AnnoyIndex

f = 40
t = AnnoyIndex(f)  # Length of item vector that will be indexed
# for i in xrange(1000):
#     v = [random.gauss(0, 1) for z in xrange(f)]
#     t.add_item(i, v)



NameError: name 'file_' is not defined

In [10]:
from annoy import AnnoyIndex
import random

f = 40
t = AnnoyIndex(f)  # Length of item vector that will be indexed
for i in xrange(1000):
    v = [random.gauss(0, 1) for z in xrange(f)]
    t.add_item(i, v)

t.build(10) # 10 trees
t.save('test.ann')

# ...

u = AnnoyIndex(f)
u.load('test.ann') # super fast, will just mmap the file
print(u.get_nns_by_item(0, 1000)) # will find the 1000 nearest neighbors

[0, 459, 762, 631, 710, 319, 346, 938, 313, 497, 180, 988, 280, 179, 719, 229, 846, 155, 81, 357, 578, 582, 825, 271, 362, 457, 464, 570, 840, 57, 545, 506, 60, 360, 302, 27, 498, 951, 168, 953, 728, 324, 928, 43, 359, 817, 451, 952, 546, 668, 893, 41, 870, 944, 548, 905, 849, 601, 766, 682, 756, 201, 318, 484, 780, 316, 15, 740, 900, 632, 872, 282, 149, 156, 96, 613, 438, 77, 452, 208, 658, 989, 361, 937, 864, 191, 852, 225, 911, 227, 786, 53, 423, 959, 549, 638, 579, 624, 58, 307, 8, 933, 267, 738, 140, 54, 419, 930, 641, 913, 619, 476, 304, 697, 82, 391, 334, 345, 674, 400, 49, 760, 923, 961, 328, 978, 554, 617, 562, 184, 535, 132, 970, 854, 974, 150, 863, 927, 992, 769, 409, 678, 513, 446, 148, 240, 157, 901, 432, 950, 16, 203, 663, 380, 86, 754, 268, 166, 512, 421, 517, 163, 725, 742, 71, 341, 265, 83, 28, 14, 256, 734, 566, 805, 462, 699, 793, 729, 765, 746, 294, 947, 515, 611, 739, 279, 269, 568, 74, 906, 885, 772, 539, 583, 142, 486, 935, 855, 553, 684, 779, 260, 896, 358, 171,

In [7]:
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer 

tfidf = TfidfVectorizer()
corpus = 5 * ['blah']
arr= tfidf.fit_transform(corpus)

arr.toarray()

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [8]:
!pwd

/Users/ajay/Documents/take_homes/NLP ML Engineering ASAPP Challenge/markov_model
